const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, 'src', 'data', 'questions.json');
const questions = JSON.parse(fs.readFileSync(FILE, 'utf8'));

const explanations = {
  601: "新しいVLANにインターネット接続を確立するには、NATのinside設定にそのVLANインターフェースを含め、ACLで送信元サブネットを許可し、ルーティング設定を更新します。",
  602: "多要素認証のスマートフォンが紛失/盗難された場合、そのデバイスのトークンを無効化（revoke）する必要があります。管理者がアカウントのMFA登録をリセットします。",
  603: "ファイアウォールがステートフルインスペクションを実行します。TCP/UDPセッションの状態を追跡し、確立された接続に属するパケットのみを許可して不正なトラフィックをブロックします。",
  604: "switchport port-security mac-address stickyコマンドにより、スイッチが動的に学習したMACアドレスを自動的にrunning-configに追加し、永続的なセキュアMACアドレスとして保持します。",
  605: "Telnet接続でローカル認証を使用するには、VTY回線にlogin localを設定し、username/passwordを作成します。transport input telnetも必要です。",
  606: "aaa new-modelコマンドはルーターでAAA（Authentication, Authorization, Accounting）を有効にし、ローカル認証からRADIUS/TACACS+ベースの認証に移行するための基盤を提供します。",
  607: "ポートセキュリティ違反時のshutdownモード（デフォルト）: (1)ポートがerr-disabled状態になる、(2)セキュリティ違反カウンターが増加。回復にはshutdown → no shutdownが必要です。",
  608: "ネットワークデバイス監視で最高のセキュリティを実現するにはSNMPv3（authPriv）を使用します。認証（MD5/SHA）と暗号化（DES/AES）の両方を提供し、コミュニティストリングの平文送信を回避します。",
  609: "show port-securityの出力から: (1)セキュアMACアドレスの最大数と現在の数、(2)違反モード（shutdown/restrict/protect）と発生状況を読み取ります。",
  610: "show port-security interfaceの出力から、ポートのセキュリティステータス、違反モード、最大MACアドレス数、現在のセキュアアドレス数、違反カウントを確認します。",
  611: "設定コマンドの効果を分析: ACLの適用、ポートセキュリティの設定、NAT/DHCPの設定などの結果として、どのトラフィックが許可/拒否されるか、どの機能が有効になるかを判断します。",
  612: "Authentication（認証）=ユーザーの身元確認（誰であるか）。Authorization（認可）=認証されたユーザーに対するアクセス権限の制御（何ができるか）。認証が先に行われます。",
  613: "WPA2-PSKのWLAN設定でWLC GUIで選択可能なフォーマット: ASCII（8-63文字のパスフレーズ）とHexadecimal（64文字の16進数鍵）です。",
  614: "AAA機能の分類: Authentication=ユーザー識別（ログイン認証）、Authorization=アクセス権限の制御（コマンド認可）、Accounting=操作記録（ログ取得）。",
  615: "未使用ポートの保護: (1)未使用ポートをshutdownで無効化、(2)未使用ポートを使用していないVLAN（ブラックホールVLAN）に移動。物理的なアクセス防止も重要です。",
  616: "フィッシング攻撃の一種です。正規の組織を装ったメール内のリンクをクリックさせ、偽のWebサイトに誘導して認証情報を窃取したり、マルウェアをダウンロードさせます。",
  617: "WLCセキュリティ設定: Layer 2=WPA/WPA2/WPA3、802.1X認証。Layer 3=Webポリシー（Web認証）。AAA=RADIUS/TACACS+サーバー設定。",
  618: "WLCのCPU ACL（Management Access Control）を有効にすると、特定のIPサブネットからのみ管理アクセス（HTTP/HTTPS/SSH/Telnet）を許可し、それ以外を拒否できます。",
  619: "多要素認証（MFA）: 2つ以上の異なるカテゴリの認証要素の組み合わせ。知識（パスワード）+ 所持（トークン/スマートカード）+ 生体（指紋/顔認証）。同じカテゴリの2つは不可。",
  620: "SSH用RSA鍵の生成には: (1)hostnameの設定、(2)ip domain-nameの設定が前提条件。その後crypto key generate rsaで鍵を生成します。",
  621: "拡張ACLの問題: 送信元/宛先IPアドレスとポートの指定が正しいか確認。ACLの適用位置（in/out）と方向が意図通りか確認。拡張ACLは送信元に近い位置に適用するのがベストプラクティス。",
  622: "WPA2-PSKの最強暗号化はAES（Advanced Encryption Standard）/CCMP（Counter Mode with CBC-MAC Protocol）です。TKIPはWPAの暗号化で、AESより弱いです。",
  623: "攻撃軽減技術: DHCPスヌーピング=DHCPスプーフィング対策、DAI=ARPスプーフィング対策、IPソースガード=IPスプーフィング対策、PortSecurity=MACフラッディング対策。",
  624: "SSH拒否のACL: access-list [番号] deny tcp host [PC-1 IP] any eq 22で特定ホストからのSSHを拒否し、access-list permit ip any anyで他を許可。VTY回線またはインターフェースに適用します。",
  625: "ACLが機能しない原因: (1)ACLの最後に暗黙のdeny allがあるが明示的なpermit文がない、(2)ACLがインターフェースに適用されていない、(3)方向（in/out）が間違っている可能性。",
  626: "service password-encryptionはrunning-config内のすべての平文パスワードをType 7暗号化（弱い暗号化）で暗号化します。enable secretのMD5/SHA256ハッシュとは異なります。",
  627: "WPA3のSAE（Simultaneous Authentication of Equals）はオフライン辞書攻撃を防ぎ、OWE（Opportunistic Wireless Encryption）は個々の接続を暗号化してトラフィック傍受を防ぎます。",
  628: "show port-security interfaceの出力でsticky MACアドレスが設定されている場合、そのポートにはPCやプリンターなどのエンドデバイスが接続されています。",
  629: "enable secret [password]コマンドはパスワードをMD5/SHA-256ハッシュで保存します。enable password（Type 7）より安全です。4台すべてに同じ設定を適用します。",
  630: "ACLやポートセキュリティの設定効果を分析: どのトラフィックが許可/拒否されるか、どのインターフェースに適用されるか、方向（in/out）を考慮して動作を判断します。",
  631: "サイト間VPNでユーザーデータの転送にはIPsec（Internet Protocol Security）が使用されます。ESP（Encapsulating Security Payload）がデータの暗号化と認証を提供します。",
  632: "WPA2-PSK（事前共有鍵モード）ではAES-CCMP暗号化が使用されます。AES（Advanced Encryption Standard）は128ビットブロック暗号で、WPA2の必須暗号化アルゴリズムです。",
  633: "IPv6リンクローカルアドレス（FE80::/10）は同一リンク内でのみ有効でルーティング不可。ユニークローカルアドレス（FC00::/7）は組織内部で使用可能でルーティング可能ですがインターネットには到達不可。",
  634: "service password-encryptionコマンドはrunning-configに平文で保存されているパスワードをType 7暗号化で保護します。ただしenable secretはより強力なハッシュを使用します。",
  635: "拡張ACLでHTTPをブロック: access-list [番号] deny tcp [送信元サブネット] [ワイルドカード] host [サーバーIP] eq 80で、特定VLANからWebサーバーへのHTTPを拒否します。",
  636: "パスワードマネージャーの利点: (1)各サービスに一意の複雑なパスワードを生成・使用できる（パスワードの再利用防止）、(2)暗号化されたデータベースに安全に保管する。",
  637: "プライベートIPv4アドレス（RFC 1918: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16）はパブリックIPの節約とNATによるセキュリティ向上（内部ネットワークの隠蔽）を実現します。",
  638: "ダイナミックARPインスペクション（DAI）はARP spoofing/poisoning攻撃を軽減します。DHCPスヌーピングバインディングテーブルに基づいてARPパケットの正当性を検証し、不正なARPを破棄します。",
  639: "リモートアクセスVPNは個々のユーザー（在宅勤務者等）が公衆インターネット経由で企業ネットワークに安全に接続する機能を提供します。IPsecまたはSSL/TLSベースのトンネルを使用します。",
  640: "未使用ポートの保護: (1)未使用ポートをshutdownで無効化、(2)ポートセキュリティを有効にしてMACアドレス数を制限。物理的なロックや監視カメラも有効な対策です。",
  641: "SSHアクセスのACL設定: 拡張ACLで送信元10.20.1.0/24からルーターへのTCPポート22を許可し、VTY回線にaccess-class [ACL番号] inで適用します。",
  642: "restrict違反モードはポートをシャットダウンせずに違反パケットを破棄し、違反カウンターを増加させ、SNMP トラップやsyslogメッセージを生成します。",
  643: "VLANホッピング攻撃の防止: (1)未使用ポートをアクセスモードに固定（switchport mode access）、(2)DTPを無効化（switchport nonegotiate）、(3)ネイティブVLANをデフォルトから変更。",
  644: "DHCPスヌーピング情報はスイッチのDHCPスヌーピングバインディングテーブル（データベース）に保持されます。MACアドレス、IPアドレス、VLAN、ポートの対応が記録されます。",
  645: "SSH設定要件: (1)hostname設定、(2)ip domain-name設定、(3)crypto key generate rsa（RSA鍵ペア生成）、(4)VTY回線でtransport input ssh、(5)login local + username設定。",
  646: "WLC GUIでWPA2-PSKを設定する場合、ASCII形式（8-63文字のパスフレーズ）がサポートされます。Hexは64文字の16進数文字列です。",
  647: "VTYアクセス保護のACL: access-list [番号] permit [許可する送信元ネットワーク] [ワイルドカード]で管理用ネットワークを許可し、VTY回線にaccess-class [番号] inで適用します。",
  648: "WLCの管理セキュリティ向上のため、HTTPとTelnetを無効にし、HTTPS（SSL/TLS）とSSHのみを使用します。暗号化されていないプロトコルは認証情報の漏洩リスクがあります。",
  649: "バッジリーダーによる入退室管理は物理アクセス制御（Physical Access Control）に分類されます。認可された人員のみが施設にアクセスできるようにするセキュリティ対策です。",
  650: "DHCPスヌーピングは信頼できないポートからのDHCPサーバー応答（OFFER/ACK）をブロックし、不正なDHCPサーバーによるアドレス配布を防止します。バインディングテーブルも構築します。",
  651: "enable secret [パスワード]コマンドでenableパスワードをMD5/SHA-256ハッシュで設定します。enable passwordがある場合、enable secretが優先されます。",
  652: "SSH（Secure Shell）はセキュアなリモートCLIアクセスを提供するプロトコルです。すべての通信を暗号化し、Telnet（平文）の代替として使用されます。TCPポート22を使用します。",
  653: "最強の暗号化: WPA3-Enterprise + AES-256-GCMP（Galois/Counter Mode Protocol）。WPA3はSAEによる認証強化とより長い暗号化鍵をサポートします。",
  654: "物理アクセス制御は施設、データセンター、サーバールーム等への物理的なアクセスを規制します。ロック、バッジ、生体認証、監視カメラ等が使用されます。",
  655: "未使用ポートの保護: 未使用ポートをshutdownで無効化し、使用していないVLAN（ブラックホールVLAN）に割り当てます。デフォルトVLAN 1からは移動させるべきです。",
  656: "WPA2-PSK のASCIIフォーマットでは最小8文字のパスフレーズが必要です。最大63文字まで設定可能で、長いパスフレーズほどセキュリティが向上します。",
  657: "GRE over IPsecはリモートサイト間でマルチキャストトラフィックを伝送（GREがマルチキャストカプセル化）し、暗号化（IPsecが暗号化）をサポートするメカニズムです。",
  658: "ACL設定: permit ip [Gi0/0サブネット] [ワイルドカード] anyでGi0/0のトラフィックを許可し、deny ip [Gi0/1サブネット] [ワイルドカード] anyでGi0/1を拒否します。暗黙のdeny allに注意。",
  659: "セキュアなリモートアクセスの設定: (1)crypto key generate rsa（RSA鍵生成）、(2)transport input ssh（VTY回線でSSHのみ許可）。前提としてhostname、ip domain-nameが必要です。",
  660: "RADIUSは認証と認可を1つのプロセスで処理するため、きめ細かいコマンド認可（per-command authorization）が困難です。TACACS+は認証・認可・アカウンティングを個別に処理できます。",
  661: "物理アクセス制御の実装: バッジリーダー、生体認証（指紋/虹彩）、マンTrap、監視カメラ、ケーブルロック等の物理的セキュリティ対策を施設に導入します。",
  662: "RADIUSのaccess-requestパケットではパスワードフィールドのみが暗号化されます。ユーザー名やその他の属性は平文で送信されます。TACACS+は全パケットを暗号化します。",
  663: "パスワード設定の優先順位: enable secretがenable passwordより優先される。コンソールにはline con 0 → password → login、VTYにはline vty → password → loginを設定します。",
  664: "MACアドレス学習: スイッチは受信フレームの送信元MACアドレスと受信ポートをMACアドレステーブルに記録します。エントリはエージングタイマー（デフォルト300秒）後に削除されます。",
  665: "ポートセキュリティ設定: switchport port-security, switchport port-security maximum [数], switchport port-security violation [shutdown/restrict/protect]で不正なMACアドレスからのトラフィックを制限します。",
  666: "OWE（Opportunistic Wireless Encryption）はオープンネットワークでパスワードなしに暗号化された接続を提供します。Diffie-Hellman鍵交換で個別の暗号化セッションを確立します。",
  667: "AAA機能の分類: Authentication=ユーザーの身元確認（ログイン）、Authorization=アクセス権限の付与（何ができるか）、Accounting=操作の記録（何をしたか）。",
  668: "802.11r（Fast BSS Transition）を有効にするには、WLCのWLAN設定でFT（Fast Transition）を有効化します。PMK（Pairwise Master Key）キャッシングも関連します。",
  669: "802.11w（Protected Management Frames/PMF）はWLAN設定のAdvancedタブでMFP（Management Frame Protection）として設定します。Required/Optionalを選択します。",
  670: "WPA3はSAE（Simultaneous Authentication of Equals）による認証とAES-GCMP-256暗号化を使用します。WPA2のAES-CCMPより強力な暗号化を提供します。",
  671: "純粋なIPsec（GREなしの場合）はユニキャストIPトラフィックのみをサポートします。マルチキャストやブロードキャストはサポートしないため、それらが必要な場合はGRE over IPsecを使用します。",
  672: "認証（Authentication）=ユーザーの身元を確認するプロセス（ID/パスワード検証）。認可（Authorization）=認証済みユーザーに対してアクセスできるリソースや実行できる操作を制御するプロセス。",
  673: "RSA鍵の生成にはcrypto key generate rsaコマンドを実行します。前提としてhostname、ip domain-nameが設定されている必要があります。鍵長は2048ビット以上が推奨されます。",
  674: "TCP SYNフラッド攻撃はハーフオープンTCP接続でターゲットのリソースを枯渇させるDoS攻撃です。大量のSYNパケットを送信し、SYN-ACKへの応答（ACK）を返さないことでリソースを消費します。",
  675: "PKI（Public Key Infrastructure）のコンポーネント: (1)CA（Certificate Authority）=証明書を発行・管理、(2)デジタル証明書=公開鍵と所有者の身元を結びつける。CRL、RA等も含まれます。",
  676: "AAA: Authentication=ユーザーが誰かを確認、Authorization=ユーザーが何にアクセスできるかを制御、Accounting=ユーザーの行動を記録・追跡。",
  677: "コンソールポートのローカル認証: line con 0 → login local。ユーザー名/パスワードはusername [名前] secret [パスワード]で作成します。RADIUS障害時のバックアップにもなります。",
  678: "WPA3はSAE（Simultaneous Authentication of Equals）を使用し、Perfect Forward Secrecy（前方秘匿性）を提供します。セッション鍵が漏洩しても過去の通信は解読できません。",
  679: "ゼロデイエクスプロイトは、ソフトウェアベンダーがまだ認識していない脆弱性（パッチ未提供）を悪用する攻撃です。発見日が「Day Zero」であるため検出・防御が困難です。",
  680: "新しいスイッチでSSHを設定してTelnetを無効化: hostname設定、ip domain-name設定、crypto key generate rsa、transport input ssh（VTY回線）、no transport input telnet。",
  681: "多要素認証の例: (1)パスワード（知識）+ スマートカード（所持）、(2)PIN（知識）+ 指紋スキャン（生体）。同じカテゴリの2つ（例: パスワード+PIN）はMFAとして不十分です。",
  682: "認証の特徴: ユーザーの身元（アイデンティティ）を確認するプロセス。認可はアクセス権限の制御、アカウンティングは操作の記録であり、身元確認は認証固有の機能です。",
  683: "Cisco AMP（Advanced Malware Protection）for Next-Gen IPSは、ファイルのリアルタイム分析、マルウェア検出、レトロスペクティブセキュリティ（過去の脅威の追跡）機能を提供します。",
  684: "WPA（Wi-Fi Protected Access）の特徴: TKIP（Temporal Key Integrity Protocol）暗号化を使用、WEPの脆弱性を改善、動的な鍵変更（per-packet key mixing）を導入。WPA2のAESより弱い。",
  685: "セキュリティのベストプラクティス: (1)多層防御（Defense in Depth）を実装、(2)定期的なセキュリティ監査とパッチ適用。最小権限の原則、ネットワークセグメンテーションも重要です。",
  686: "WPA3はSAE（Simultaneous Authentication of Equals）でオフライン辞書攻撃を防ぎ、Perfect Forward Secrecyで過去の通信を保護し、192ビットセキュリティスイートでエンタープライズを強化します。",
  687: "次世代IPS（NGIPS）の機能: アプリケーション認識と制御、コンテキスト認識（ユーザー、デバイス）、マルウェア検出、脆弱性ベースのシグネチャ、レトロスペクティブ分析。",
  688: "AAA機能: Authentication=ログイン時のユーザー認証、Authorization=コマンドやリソースへのアクセス制御、Accounting=セッション時間やコマンド使用の記録。",
  689: "セキュリティプログラム要素: 物理アクセス制御=施設への入退管理、論理アクセス制御=ネットワーク/システムへのアクセス管理、セキュリティポリシー=組織のルール定義。",
  690: "IPsecのトンネルモードは元のIPヘッダーとペイロード全体を暗号化し、新しいIPヘッダーでカプセル化します。トランスポートモードはペイロードのみ暗号化し元のIPヘッダーは保持します。",
  691: "トランクリンクでのデフォルトのポートセキュリティ動作はdisabled（無効）です。ポートセキュリティはデフォルトでアクセスポートにのみ設定可能で、トランクでは明示的な有効化が必要です。",
  692: "ファイアウォールはセキュリティドメイン（信頼ゾーン/非信頼ゾーン）間でネットワークを分離するデバイスです。ACL、ステートフルインスペクション、アプリケーションフィルタリングを実行します。",
  693: "VLANホッピング攻撃の軽減: (1)アクセスポートでswitchport mode access（DTPフレームを送信しない）、(2)switchport nonegotiateでDTP無効化、(3)ネイティブVLANをVLAN 1以外に変更。",
  694: "WPA3の強化機能: SAE（Simultaneous Authentication of Equals）による安全な鍵交換。パスワードがブルートフォース攻撃やオフライン辞書攻撃に対して耐性があります。",
  695: "IPsecトンネルモードは元のIPパケット全体（ヘッダー+ペイロード）をカプセル化して暗号化します。サイト間VPNで使用され、新しいIPヘッダーが追加されます。",
  696: "SSH接続用ACLをVTY回線に適用: access-class [ACL番号] inで指定サブネットからのみSSH接続を許可します。ACLで10.139.58.0/28を許可し、暗黙のdenyで他を拒否します。",
  697: "SDNアーキテクチャではコントロールプレーン機能（ルーティング判断、パス計算）がコントローラーに集中化されます。データプレーン（パケット転送）は各ネットワークノードに残ります。",
  698: "ユーザー名とパスワードでデバイスにログインするプロセスは認証（Authentication）です。AAAの最初のA＝ユーザーの身元（アイデンティティ）を確認するセキュリティプロセス。",
  699: "LDAP認証で最高のセキュリティ: (1)WPA3-Enterprise（または最低WPA2-Enterprise）を選択、(2)AES暗号化を使用。802.1X/EAP認証でRADIUS経由のLDAP認証を設定します。",
  700: "WPA3の強化機能: SAE（オフライン辞書攻撃耐性）、Forward Secrecy（過去の通信保護）、192ビットセキュリティスイート（Enterprise）、OWE（オープンネットワーク暗号化）。"
};

let updated = 0;
for (const q of questions) {
  if (explanations[q.number]) {
    q.explanation = explanations[q.number];
    updated++;
  }
}

fs.writeFileSync(FILE, JSON.stringify(questions, null, 2), 'utf8');
console.log(`Done: added explanation to ${updated} questions (601-700).`);
