const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, 'src', 'data', 'questions.json');
const questions = JSON.parse(fs.readFileSync(FILE, 'utf8'));

const explanations = {
  501: "VRRPの仮想MACアドレスは0000.5E00.01XX形式（XXはグループ番号の16進数）です。RFC 5798で定義されたオープンスタンダードのFHRPプロトコルです。",
  502: "VRRPはオープンスタンダード（RFC 5798）のFHRPで、マルチベンダー環境でデフォルトゲートウェイの冗長性を提供します。HSRPはCisco独自のためマルチベンダーではVRRPが適切です。",
  503: "VRRPを導入する理由: デフォルトゲートウェイの冗長性を提供し、プライマリルーター障害時にバックアップルーターが自動的に引き継ぐことで、ネットワークの可用性を向上させます。",
  504: "HSRPでルーター間で共有されホストのデフォルトゲートウェイとして使用されるのは仮想IPアドレスです。実際のインターフェースIPとは別に設定され、アクティブルーターが応答します。",
  505: "HSRPグループ14の仮想MACアドレス: 0000.0C07.AC0E（0Eはグループ番号14の16進数）。HSRPの仮想MAC形式は0000.0C07.ACXX（XXはグループ番号の16進）です。",
  506: "OSPFネットワークの到達性問題: ルーター追加時にnetworkコマンドで正しいインターフェースとエリアを含め、隣接ルーターとの接続性を確認する必要があります。",
  507: "同じOSPFプロセスで同じ宛先への2つのスタティックルート（異なるネクストホップ）がある場合、両ルートがルーティングテーブルにインストールされ、Equal-Costロードバランスが行われます。",
  508: "FHRPはデフォルトゲートウェイルーターの障害（単一障害点）から保護します。物理ルーター障害時に仮想IPアドレスが別のルーターに引き継がれ、ホストの通信が継続します。",
  509: "IP SLAでUDPジッターを測定するには、宛先デバイスにIP SLA Responderが設定されている必要があります。Responderはプローブパケットに応答してジッター計測を可能にします。",
  510: "設定コマンドからNAT、DHCP、ACL、QoSなどの有効化される機能を識別します。ip natコマンドはNAT、ip dhcp poolはDHCPサーバー、service-policyはQoSを有効にします。",
  511: "NATプールはNAT変換に使用可能なパブリックIPアドレスのグループです。ip nat pool [名前] [開始IP] [終了IP] netmask [マスク]で定義します。",
  512: "VTY回線でSSHとTelnet両方をサポートするには transport input all または transport input ssh telnet を設定します。transport input sshのみだとTelnetは拒否されます。",
  513: "DHCPクライアントがサブネット外と通信できない場合、デフォルトゲートウェイ（default-router）がDHCPプール設定に含まれていない可能性があります。default-routerコマンドで設定します。",
  514: "DHCPサーバーでIPアドレスの競合が検出された場合、そのアドレスはプールから除外されクライアントには割り当てられません。ip dhcp ping packetsで競合検出を設定します。",
  515: "show ip dhcp bindingコマンドでDHCPサーバーが割り当てたIPアドレス、MACアドレス、リース期限の一覧を確認できます。",
  516: "DNS（Domain Name System）において権威ある情報源は権威DNSサーバー（Authoritative DNS Server）です。そのゾーンに対する正式なDNSレコードを保持しています。",
  517: "show ip interface [interface]コマンドまたはshow running-config interface [interface]でDHCPリレーエージェント（ip helper-address）の設定を確認できます。",
  518: "DHCPサーバーはIPアドレスバインディング（IPアドレス、MACアドレス、リース期間の対応表）を保持します。プール設定にはサブネット、デフォルトゲートウェイ、DNS等も含みます。",
  519: "DNSの役割: (1)ホスト名からIPアドレスへの正引き解決（A/AAAAレコード）、(2)IPアドレスからホスト名への逆引き解決（PTRレコード）。ネットワーク通信の基盤サービスです。",
  520: "インターフェースがDHCPで設定されていることを確認するには show ip interface [interface] を実行し、「Address determined by DHCP」の表示を確認します。",
  521: "logging trap debugを設定すると、すべてのsyslogレベル（0:Emergency〜7:Debug）のメッセージがsyslogサーバーに送信されます。debugは最も詳細なレベルです。",
  522: "logging trap 3はError（レベル3）以上の重大度メッセージを送信します。Emergency(0)、Alert(1)、Critical(2)、Error(3)の3レベルがsyslogサーバーに送信されます。",
  523: "ネットワークプロトコルとトランスポート: HTTP/HTTPS=TCP、DNS=UDP/TCP、DHCP=UDP、FTP=TCP、TFTP=UDP、SNMP=UDP、SSH/Telnet=TCP、NTP=UDP。",
  524: "SNMPを使用してルーター設定をバックアップするには、SNMP MIBオブジェクト（ciscoConfigManMIB等）を利用してNMSからリモートでcopy running-config操作を実行できます。",
  525: "インターフェースをDHCPクライアントにするには ip address dhcp コマンドをインターフェースコンフィギュレーションモードで設定します。DHCPサーバーからIPアドレスを自動取得します。",
  526: "SNMPエージェントはネットワークデバイス上で動作し、MIB情報を収集・保持し、NMS（Network Management Station）からのGet/Set要求に応答し、Trapを送信します。",
  527: "DHCPの役割: (1)IPアドレスの動的割り当て（クライアントにIPアドレスを自動配布）、(2)ネットワークパラメータの配布（デフォルトゲートウェイ、DNSサーバー、リース期間等）。",
  528: "デバイスをNTPサーバーとして設定するには ntp master [stratum] コマンドを使用します。stratum値はNTP階層レベルを指定します（低いほど信頼度が高い）。",
  529: "Syslog Notice（レベル5）メッセージは、正常だが重要な状態を示します。通常の運用で注意すべきイベント（インターフェースのup/down等）が記録されます。",
  530: "R1のIPをDHCPから取得するには: (1)R1のインターフェースにip address dhcpを設定、(2)DHCPサーバーへの到達性を確保（同一ブロードキャストドメインまたはリレー設定）。",
  531: "WRED（Weighted Random Early Detection）: (1)輻輳が発生する前にランダムにパケットを破棄して輻輳を予防、(2)IPプレシデンスやDSCP値に基づいて異なる破棄確率を適用。TCPスロースタートの同期を防ぎます。",
  532: "NAT変換後の送信元IPはip nat poolで定義されたアドレスまたはオーバーロード（PAT）の場合はインターフェースのパブリックIPです。設定のinsideとoutsideの指定を確認します。",
  533: "Syslog Noticeレベル（5）は正常だが注意を要する状態を報告します。例: ネイバー関係の確立、設定変更の通知など。Critical(2), Error(3), Warning(4)より軽微です。",
  534: "ネットワークコンポーネントの機能分類: NMS=SNMPマネージャー（監視・管理）、Agent=デバイス上のSNMPプロセス（情報収集）、MIB=管理情報データベース。",
  535: "NTPクライアントモードの設定: (1)ntp server [IPアドレス]でNTPサーバーを指定、(2)ntp authenticateとntp authentication-key/ntp trusted-keyで認証を有効化。",
  536: "FHRPの主な目的: デフォルトゲートウェイの冗長性を提供し、プライマリゲートウェイ障害時にホストの設定変更なしで自動的にバックアップゲートウェイに切り替えます。",
  537: "ダイナミックNATの設定: ip nat pool（3つのアドレス定義）、access-list（対象送信元）、ip nat inside source list [ACL] pool [名前]で変換を有効にします。",
  538: "HSRPでアクティブルーター障害時は、スタンバイルーター（2番目に高いプライオリティ）が自動的にアクティブに昇格し、仮想IPアドレスへのトラフィックを処理します。",
  539: "copyコマンドでのバックアップにはTFTP、FTP、SCP等のプロトコルが使用できます。copy running-config tftp:でTFTPサーバーにバックアップ可能です。",
  540: "NATデバイスのパブリックIPアドレスはOutside Local/Outside Global（外部アドレス）に分類されます。NAT用語: Inside Local=内部プライベートIP、Inside Global=変換後のパブリックIP。",
  541: "show ntp statusの出力: (1)クロックの同期状態（synchronized/unsynchronized）、(2)参照先NTPサーバーのIPアドレスとstratum値。rootディスパージョンやオフセットも表示されます。",
  542: "overloadキーワードにより PAT（Port Address Translation）が有効になり、複数の内部ホストが1つの外部IPアドレスを共有します。ポート番号で各セッションを区別します。",
  543: "IP SLA（Service Level Agreement）はネットワーク上のQoS品質（遅延、ジッター、パケットロス）を測定し、IPサービスのパフォーマンスが十分かどうかを判断します。",
  544: "LLQ（Low-Latency Queuing）は対話型の音声・ビデオトラフィックに適した優先キューイング方式です。priority queueに設定されたトラフィックを他のキューより優先的に処理します。",
  545: "SNMPコンポーネント: Manager(NMS)=ネットワーク監視・制御、Agent=デバイス上で情報収集、MIB=管理オブジェクトのデータベース、Trap=エージェントからの非同期通知。",
  546: "トラフィックシェーピングは出力トラフィックを指定した帯域幅に制限し、超過パケットをバッファに保持して後で送信します。ポリシングとは異なりパケットを破棄しません。",
  547: "TFTPはIOSイメージやコンフィグファイルの転送に使用される簡易ファイル転送プロトコルです。UDP使用、認証なし、小さいファイルの転送に適しています。",
  548: "DHCPクライアントはDHCPサーバーからIPアドレスやネットワーク設定を動的に取得するデバイスです。DORA（Discover/Offer/Request/Ack）プロセスでアドレスを取得します。",
  549: "ip helper-addressはDHCPリレーが必要なインターフェース（クライアント側のゲートウェイインターフェース）に設定します。DHCPブロードキャストをユニキャストに変換してサーバーに転送します。",
  550: "DNSがデバイス名をIPアドレスに解決することで、ホスト名を使用したTelnet接続が可能になります。ip name-server と ip domain-lookup の設定が必要です。",
  551: "Syslogの重大度レベル6が「Informational」（情報）です。レベル: 0=Emergency、1=Alert、2=Critical、3=Error、4=Warning、5=Notice、6=Informational、7=Debug。",
  552: "スタティックNATの設定: (1)ip nat inside source static [内部IP] [外部IP]、(2)inside/outsideインターフェースの指定（ip nat inside / ip nat outside）。",
  553: "輻輳管理のQoSツール: (1)CBWFQ（Class-Based Weighted Fair Queuing）=クラスごとに帯域幅を保証、(2)LLQ（Low-Latency Queuing）=優先キューで遅延に敏感なトラフィックを処理。",
  554: "LLQ（Low-Latency Queuing）はデータ中心のネットワークで音声トラフィックを最適化するQoSツールです。音声パケットに優先キューを提供し、遅延とジッターを最小化します。",
  555: "スタティックIPのデバイスがDHCPと競合しないように、DHCPプール設定でip dhcp excluded-addressコマンドを使用してプリンターのIPアドレスをDHCP割り当てから除外します。",
  556: "DHCPリレーエージェント（通常はルーター）が異なるサブネット間でDHCPメッセージを転送します。ip helper-addressコマンドでDHCPサーバーのIPを指定します。",
  557: "NTPの階層: ntp serverコマンドでクライアントとして設定されたルーターは、参照サーバーのstratum+1の値を持ちます。ntp masterコマンドでサーバーとして動作させることも可能です。",
  558: "FTP（File Transfer Protocol）とSCP（Secure Copy Protocol）は認証（ユーザー名/パスワード）を必要とします。TFTPは認証なしで動作する簡易プロトコルです。",
  559: "NMSがSNMPトラップを処理するには: (1)NMSでトラップ受信を有効化、(2)エージェントにsnmp-server host [NMS-IP] trapsを設定、(3)コミュニティストリングが一致していること。",
  560: "上位NTPサーバーとの接続失敗時にスイッチ自体をNTPサーバーにするには ntp master [stratum] コマンドを設定します。内部クロックを基準としてNTPサービスを提供します。",
  561: "DHCPリレーにはip helper-address [DHCPサーバーIP]をクライアント側インターフェースに設定します。これによりDHCP Discoverブロードキャストがユニキャストでサーバーに転送されます。",
  562: "情報レベルのsyslog（レベル6: Informational）を取得するにはlogging trap 6またはlogging trap informationalを設定します。レベル6以下（0-6）のメッセージが送信されます。",
  563: "Microsoft Windowsワークステーションにデフォルトゲートウェイを提供するプロトコルはDHCPです。DHCPサーバーがIPアドレスと共にデフォルトゲートウェイ情報を配布します。",
  564: "NTPの動作: (1)クライアントはサーバーに周期的にポーリングして時刻を同期、(2)Stratum値でNTPソースの信頼性を示す（Stratum 1が最も正確）。UDP ポート123を使用します。",
  565: "特定VLANのPAT設定: access-listでVLAN 200のサブネットを指定し、ip nat inside source list [ACL] interface [外部IF] overloadでPATを有効にします。VLAN 100は変換しないので除外します。",
  566: "暗号化接続（SSH）のみを受け入れるには: (1)transport input ssh（VTY回線でSSHのみ許可）、(2)crypto key generate rsa（RSA鍵の生成）が必要です。Telnetは暗号化なしのため除外します。",
  567: "SNMPv3はsnmp-server group [名前] v3 [セキュリティレベル]コマンドで設定します。セキュリティレベル: noauth（認証なし）、auth（認証あり）、priv（認証+暗号化）。",
  568: "NTPサーバーの設定: ntp authenticate（認証有効化）、ntp authentication-key [ID] md5 [鍵]（認証キー定義）、ntp source loopback 0（送信元IF指定）、ntp master [stratum]。",
  569: "FTPはネットワーク管理でIOSイメージのアップロード/ダウンロード、設定ファイルのバックアップ/リストアに使用されます。TCP使用で認証（ユーザー名/パスワード）をサポートします。",
  570: "RSA鍵を生成するには先にip domain-nameコマンドでドメイン名を設定する必要があります。ドメイン名は鍵のラベルに使用されます。crypto key generate rsaで鍵を生成します。",
  571: "トラフィックシェーピングは設定帯域幅を超過したパケットをバッファに保持し、帯域幅が利用可能になったときに送信します。パケットを破棄するポリシングとは異なります。",
  572: "DHCPリレーの設定: クライアント側インターフェースで ip helper-address [DHCPサーバーIP] を入力します。このコマンドでDHCPブロードキャストがサーバーに転送されます。",
  573: "同じスイッチ上のDHCPサーバーとクライアントが異なるVLANにある場合、VLAN間ルーティング（SVIまたはRouter on a Stick）とip helper-addressの設定が必要です。",
  574: "ルーターの日付と時刻設定: clock set 12:00:00 January 1 2020 コマンドをEXEC（特権）モードで実行します。NTPを使用しない場合の手動時刻設定です。",
  575: "ルーティングテーブルの[AD/メトリック]表記からメトリック値を読み取ります。例えば[110/30]ならメトリックは30（OSPF）、[90/2172416]ならメトリックは2172416（EIGRP）です。",
  576: "スタティックNATの設定: ip nat inside source static 10.1.1.1 209.165.200.225。内部ローカルアドレスを内部グローバルアドレスに1対1で固定的にマッピングします。",
  577: "DHCPアドレスを受信できない原因: DHCPサーバーのアドレスプール枯渇、ip helper-addressの設定漏れ、DHCPスヌーピングでの信頼ポート設定誤り、VLAN設定の問題などが考えられます。",
  578: "TFTPの特徴: UDPポート69を使用、認証なし、小さいファイル転送向け、コネクションレスで軽量。FTPと比べて機能は制限されますがシンプルで設定が容易です。",
  579: "マーキング（Marking）はパケットヘッダーのDSCP/IPプレシデンス値やCoS値を設定するQoSパーホップビヘイビアです。下流のデバイスがこのマーキングに基づいて転送処理を決定します。",
  580: "NATの設定: ip nat inside（内部IF）、ip nat outside（外部IF）の指定と、NATルール（static/dynamic/PAT）の設定が必要です。ACLで変換対象を正しく定義します。",
  581: "ip address dhcpコマンドはインターフェースがDHCPクライアントとして動作し、DHCPサーバーからIPアドレスとネットワーク設定を自動取得するよう設定します。",
  582: "DHCPリレーの設定: R4のFa0/1インターフェースにip helper-address [DHCPサーバーIP]を設定し、DHCPブロードキャストをリモートのDHCPサーバーに転送します。",
  583: "SNMPコマンド: snmp-server community（コミュニティ設定）、snmp-server host（Trap送信先NMS指定）、snmp-server enable traps（Trap有効化）、snmp-server contact/location（システム情報）。",
  584: "SSH v2の最小設定: (1)hostname設定、(2)ip domain-name設定、(3)crypto key generate rsa（2048ビット推奨）、(4)ip ssh version 2、(5)VTY回線でtransport input ssh。",
  585: "ポリシング（Policing）は契約帯域幅を超過したパケットを即座に破棄またはマーキングダウンするQoS機能です。ISPが顧客のトラフィックを契約レートに制限するために使用します。",
  586: "QoS用語: Classification=トラフィックの分類、Marking=パケットへのQoS値付与、Queuing=キューへの振り分け、Scheduling=キューからの送信順序制御、Shaping=帯域制限（バッファリング）。",
  587: "Telnetはセキュリティ保護されていない（暗号化なし）リモートCLIアクセスプロトコルです。パスワードを含むすべてのデータが平文で送信されるため、SSHの使用が推奨されます。",
  588: "SNMP障害管理: Trap=エージェントからの自動通知、Polling=NMSからの定期的な状態確認（Get）、MIB=管理情報の格納、Threshold=閾値超過時のアラートトリガー。",
  589: "NTPクライアントはntp server [IP]コマンドで設定されたルーターです。show ntp statusで同期状態を確認し、ntp masterコマンドがないルーターがクライアントです。",
  590: "NAT設定の完了ステップ: insideとoutsideインターフェースの指定、ACLの定義、NATルール（ip nat inside source）の設定が段階的に必要です。",
  591: "Syslogファシリティはメッセージの送信元を識別するカテゴリです。OS、セキュリティ、デーモン等のプロセスが異なるファシリティ値を使用して、メッセージの分類と管理を容易にします。",
  592: "DHCP機能: DORA（Discover→Offer→Request→Ack）プロセス、IPアドレスのリース管理、ネットワークパラメータの配布（ゲートウェイ、DNS）、アドレスプールの管理。",
  593: "インターネット接続のためのNAT設定: 送信元NATルールが正しく設定されているか確認。ACLが送信元サブネットを正しく許可し、ip nat inside sourceとoverloadが設定されている必要があります。",
  594: "ポリシング（Policing）はトラフィックフローの目標ビットレート（CIR）を超えるパケットを破棄またはマーキングダウンします。バッファリングせず即座に処理するのがシェーピングとの違いです。",
  595: "マーキング（Marking）はIPv4パケットヘッダーのToS（Type of Service）フィールド内のDSCPまたはIPプレシデンス値を変更するQoSパーホップビヘイビアです。",
  596: "FTPの機能: TCP使用のファイル転送プロトコル。認証（ユーザー名/パスワード）サポート、ディレクトリ操作、大容量ファイル転送に対応。制御用（ポート21）とデータ用（ポート20）の2つの接続を使用。",
  597: "TFTPはUDPポート69を使用する簡易ファイル転送プロトコルです。認証なし、コネクションレスで軽量に動作し、IOSイメージや設定ファイルの転送に使用されます。",
  598: "QoSマーキングのベストプラクティス: ネットワークの入口（アクセスレイヤー）で可能な限り早くトラフィックを分類・マーキングし、以降のデバイスでマーキングに基づいた処理を行います（Trust Boundary）。",
  599: "QoSは音声トラフィックに優先キュー（LLQ）を割り当てて遅延を最小化し、帯域幅を保証することで音声品質を最適化します。ジッターバッファとシリアル化遅延の管理も重要です。",
  600: "LLQ（Low-Latency Queuing）はCBWFQに優先キューを追加したQoSメカニズムです。音声パケットを優先的に処理し、データネットワーク上での音声品質を確保します。"
};

let updated = 0;
for (const q of questions) {
  if (explanations[q.number]) {
    q.explanation = explanations[q.number];
    updated++;
  }
}

fs.writeFileSync(FILE, JSON.stringify(questions, null, 2), 'utf8');
console.log(`Done: added explanation to ${updated} questions (501-600).`);
